//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elca.Tools.ManorChangeScriptRunner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OracleHome {
            get {
                return ((string)(this["OracleHome"]));
            }
            set {
                this["OracleHome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Change-Scripts\\ToExecuteInVN")]
        public string ScriptsFromManor {
            get {
                return ((string)(this["ScriptsFromManor"]));
            }
            set {
                this["ScriptsFromManor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sys")]
        public string SysUser {
            get {
                return ((string)(this["SysUser"]));
            }
            set {
                this["SysUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mim_spu")]
        public string MimSpuUser {
            get {
                return ((string)(this["MimSpuUser"]));
            }
            set {
                this["MimSpuUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mim_spu")]
        public string MimSpuPassword {
            get {
                return ((string)(this["MimSpuPassword"]));
            }
            set {
                this["MimSpuPassword"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DBAora2014")]
        public string SysPassword {
            get {
                return ((string)(this["SysPassword"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Change-Scripts\\RunScript")]
        public string SqlPath {
            get {
                return ((string)(this["SqlPath"]));
            }
            set {
                this["SqlPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Change-Scripts\\ExecutedByCH")]
        public string ExecutedScripts {
            get {
                return ((string)(this["ExecutedScripts"]));
            }
            set {
                this["ExecutedScripts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\Change-Scripts\\ToExecuteInVN")]
        public string ScriptsForVN {
            get {
                return ((string)(this["ScriptsForVN"]));
            }
            set {
                this["ScriptsForVN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VKOPIES")]
        public string TNSProdu {
            get {
                return ((string)(this["TNSProdu"]));
            }
            set {
                this["TNSProdu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VFISTES")]
        public string TNSFis {
            get {
                return ((string)(this["TNSFis"]));
            }
            set {
                this["TNSFis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VHAUTES")]
        public string TNSHaus {
            get {
                return ((string)(this["TNSHaus"]));
            }
            set {
                this["TNSHaus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VMAITES")]
        public string TNSMai {
            get {
                return ((string)(this["TNSMai"]));
            }
            set {
                this["TNSMai"] = value;
            }
        }
    }
}
